### ISSUE TITLE
Generate the Knowledge Graph from the database

### ISSUE THREAD

**Issue by adrigrillo** [adrigrillo/music_kg#1]
To generate the Knowledge Graph the MusicBrainz database is used together with the Music Ontology as dictionary. This task will use as reference the [MusicBrainz-R2RML repo](https://github.com/LinkedBrainz/MusicBrainz-R2RML).

### Subtasks
- [x] Check the [MusicBrainz database schema](https://beta.musicbrainz.org/doc/MusicBrainz_Database/Schema).
- [x] Check the [Music Ontology](http://musicontology.com/specification/).
- [x] Set the relations and generate a mapping file: #3 #4 #5 
- [x] Check the Knowlege Graph generated.

**Comment by adrigrillo** [comment]
The available repository: https://github.com/LinkedBrainz/MusicBrainz-R2RML uses a library which converts from relational databases to RDF that is no longer available to download. Two possible solutions are possible:

- Generate my own RML mapping with:
  1. [Ontop](https://github.com/ontop/ontop) :-1: 
  2. [RMLMapper](https://github.com/RMLio/rmlmapper-java). Does not scale therefore not possible for this dataset size.
  3. [**R2RML**](https://github.com/amalic/r2rml). Suggested by the teacher, trying with this one.
  4. [RMLParser](https://github.com/nkons/r2rml-parser)
- Use an old dump from [here](http://www.linkedbrainz.org/LinkedBrainz201712.tgz)

The dump dates from december of 2017 but can still be used to make the interlinking and complete the information, however it won't be updated and some information can be correct currently.

**Comment by adrigrillo** [comment]
### Database
The process to open the connection to the database and allow the access from the host computer is the following:
```bash
bin/turn-port db on
docker-compose -f ~/musicbrainz/musicbrainz-docker/docker-compose.yml up -d db
```
The `docker-compose` is necessary to make the changes effective (MusicBrainz bug). The name, user and password for the database are:

- database:  `musicbrainz`
- user: `musicbrainz`
- password: `musicbrainz`

To access the database a wide range of tools can be used. The original one from PostgreSQL tool is `psql` that in Ubuntu can be installed with `sudo apt install postgresql-client` command. Other tools like DataGrip or DBeaver can be used.

### Docker
The [R2RML](https://github.com/amalic/r2rml) implementation uses a docker image that has to be build and the run. To build the image the next command is executed while being in the folder that contains the dockerfile:

```bash
docker build --rm -f "Dockerfile" -t r2rml:latest .
```

To execute the script the next command will be neccessary:

```bash
docker run -it --rm <database> -v <local dir>:/data r2rml /data/config.properties
```

To execute this script two variables have to be considered:

1. **database**: Depending where the database is hosted (in a container, the host system or external system) it will take different values:
  - host system: `--network="host"`.
  - container: `--link image_name:tag`
  - external system: nothing will be required if the container can access to the internet.
2. **local dir**: Has to be the path in the host system where the configuration file and the mapping file are located.

**Comment by adrigrillo** [comment]
For this project we have special interest in the artist, their genres and where they come from. In a way that the artist are linked to different genres and a given area (country, city or more specific location). MusicBrainz also contains some external information in form of URL that can be useful to the improve the linking process. 

### Important tables for the database

- [**Artist**](https://beta.musicbrainz.org/doc/Artist):
  - `artist` is the main table.
  - `artist_type` link the artist with a set of possible values like group, person, orchestra, etc.
  - `artist_alias` contains other names for the artist. Could be considered.

- **Genres**: Further discussion in #4:
  - `tag` contains all the tags written by the users. The genres are hardcoded in the database and can be found [here](https://raw.githubusercontent.com/metabrainz/musicbrainz-server/master/entities.json).

- [**Area**](https://beta.musicbrainz.org/doc/Area). Further discussion in #3:
  - `area` contains the regions, could be a country, region, city or something like that. They are in sync with Wikidata :+1:. The type could be useful for looking more information like the ISO code.
  - `iso_3166_1` contains the two letter ISO code of the countries that can be useful for linking.

- **URL**:
  - `url` contains the external urls of different entities of the database. We are only interested in the artist and location urls (look relations point).

- **Relations**:
  - `artist_tag` contains the tags of the artist. This is important because **relates the artist with its genre**.
  - `l_area_area` contains the relations between areas. For example, country and city.
  - `l_artist_url`contains the relations between the artist, using its id, with the the external link, using its id.

The full schema of the database is:

![schema](https://user-images.githubusercontent.com/18198342/54370235-92d50f80-4677-11e9-86fd-7252a030eb2f.png)

**Comment by adrigrillo** [comment]
The table `link` that contains the links between different elements in the tables and the table `link_type` that defines the type of relation between two elements could be very useful for building relations between artists and also between the areas. Improving the existing method to link the entities. This will be commented in their respective issues, #3 for areas and #5 for artists.
