### ISSUE TITLE
Link the KG with DBpedia and Wikidata

### ISSUE THREAD

**Issue by adrigrillo** [adrigrillo/music_kg#2]
To generate the linking between the create Knowledge Graph, DBpedia and Wikidata one of the two next available tools will be used:
- [LIMES.](https://github.com/dice-group/LIMES/)
- [Silk framework.](http://silkframework.org/)

### Subtasks
- [ ] Study the advantages and disadvantages of the tools for this task.
- [x] Examine DBpedia dictionary and entities.
- [x] Examine Wikidata dictionary and entities.
- [x] Link with DBpedia.
- [x] Link with Wikidata.
- [x] Review the links that do not overcome the certainty percentage.

**Comment by adrigrillo** [comment]
Decided to go for LIMES and linked the existent genres.
